openapi: 3.2.0
info:
  title: Lex Machina Entities API
  version: '20260324'
  description: Entity data.
servers:
- url: https://api.lexmachina.com
  description: Lex Machina production API
tags:
- name: Entities
  description: Entity data.
paths:
  /magistrate-judges/{magistrate_judge_id}:
    get:
      tags:
      - Entities
      summary: Get Magistrate
      description: 'Gets data for a single federal magistrate judge.


        - **magistrate_judge_id**: the Lex Machina magistrateJudgeId'
      operationId: get_magistrate
      security:
      - JwtAccessBearer: []
      parameters:
      - name: magistrate_judge_id
        in: path
        required: true
        schema:
          type: integer
          title: Magistrate Judge Id
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MagistrateJudgeData'
              examples:
                Single Magistrate Judge:
                  summary: Single Magistrate Judge
                  value:
                    name: Margaret J Kravchuk
                    magistrateJudgeId: 801
                    initials: MJK
                    caseCountByCourt:
                    - court: total
                      count: 1720
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Magistrate Judge Not Found:
                  summary: Magistrate Judge Not Found
                  value:
                    detail: No magistrates matching provided magistrate IDs were found
        '422':
          description: Error - 422
          content:
            application/json:
              examples:
                Invalid Input:
                  summary: Invalid Input
                  value:
                    detail:
                    - type: int_parsing
                      loc:
                      - path
                      - magistrate_judge_id
                      msg: Input should be a valid integer, unable to parse string as an integer
                      input: string
                Validation error:
                  summary: Validation error
                  value:
                    summary: Invalid input
                    detail:
                    - type: parsing
                      loc:
                      - path
                      - query
                      - body
                      msg: invalid input
                      input: '-1'
        '401':
          description: Invalid or expired token
          content:
            application/json:
              examples:
                Expired token:
                  summary: Expired token
                  value:
                    detail: 'Token time expired: Signature has expired.'
                Invalid token:
                  summary: Invalid token
                  value:
                    detail: Invalid token
  /magistrate-judges:
    get:
      tags:
      - Entities
      summary: Get Magistrates
      description: 'Gets data for a one or more federal magistrate judges.


        - **magistrateJudgeIds**: the Lex Machina magistrateJudgeIds'
      operationId: get_magistrates
      security:
      - JwtAccessBearer: []
      parameters:
      - name: magistrateJudgeIds
        in: query
        required: true
        schema:
          type: array
          uniqueItems: true
          items:
            type: integer
          minItems: 1
          maxItems: 500
          title: Magistratejudgeids
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MagistrateJudgeData'
                title: Response Get Magistrates Magistrate Judges Get
              examples:
                Multiple Magistrate Judges:
                  summary: Multiple Magistrate Judges
                  value:
                  - name: Margaret J Kravchuk
                    magistrateJudgeId: 801
                    initials: MJK
                    caseCountByCourt:
                    - court: total
                      count: 1720
                  - name: Zahid N Quraishi
                    magistrateJudgeId: 1385
                    initials: ZNQ
                    caseCountByCourt:
                    - court: total
                      count: 1212
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Multiple Magistrate Judges:
                  summary: Multiple Magistrate Judges
                  value:
                    detail: No magistrates matching provided magistrate IDs were found
        '401':
          description: Invalid or expired token
          content:
            application/json:
              examples:
                Expired token:
                  summary: Expired token
                  value:
                    detail: 'Token time expired: Signature has expired.'
                Invalid token:
                  summary: Invalid token
                  value:
                    detail: Invalid token
        '422':
          description: Error - 422
          content:
            application/json:
              examples:
                Validation error:
                  summary: Validation error
                  value:
                    summary: Invalid input
                    detail:
                    - type: parsing
                      loc:
                      - path
                      - query
                      - body
                      msg: invalid input
                      input: '-1'
  /state-judges/{state_judge_id}:
    get:
      tags:
      - Entities
      summary: Get State Judge
      description: 'Gets data on a single state judge.


        - **state_judge_id**: the Lex Machina stateJudgeId'
      operationId: get_state_judge
      security:
      - JwtAccessBearer: []
      parameters:
      - name: state_judge_id
        in: path
        required: true
        schema:
          type: integer
          title: State Judge Id
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StateJudgeData'
              examples:
                Single State Judge:
                  summary: Single State Judge
                  value:
                    name: Daryl L Moore
                    stateJudgeId: 775
                    courtPosting: Texas District Court, 333rd Judicial District
        '401':
          description: Invalid or expired token
          content:
            application/json:
              examples:
                Expired token:
                  summary: Expired token
                  value:
                    detail: 'Token time expired: Signature has expired.'
                Invalid token:
                  summary: Invalid token
                  value:
                    detail: Invalid token
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Not found:
                  summary: Not found
                  value:
                    summary: Unknown id
                    detail: Not Found
        '422':
          description: Error - 422
          content:
            application/json:
              examples:
                Validation error:
                  summary: Validation error
                  value:
                    summary: Invalid input
                    detail:
                    - type: parsing
                      loc:
                      - path
                      - query
                      - body
                      msg: invalid input
                      input: '-1'
  /state-judges:
    get:
      tags:
      - Entities
      summary: Get State Judges
      description: 'Gets data on one or more single state judges.


        - **stateJudgeIds**: the Lex Machina stateJudgeIds'
      operationId: get_state_judges
      security:
      - JwtAccessBearer: []
      parameters:
      - name: stateJudgeIds
        in: query
        required: true
        schema:
          type: array
          uniqueItems: true
          items:
            type: integer
          minItems: 1
          maxItems: 500
          title: Statejudgeids
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StateJudgeData'
                title: Response Get State Judges State Judges Get
              examples:
                Multiple State Judges:
                  summary: Multiple State Judges
                  value:
                  - name: Sheila Abdus-Salaam
                    stateJudgeId: 2087
                    courtPosting: New York Supreme Court, New York County
                  - name: Daryl L Moore
                    stateJudgeId: 775
                    courtPosting: Texas District Court, 333rd Judicial District
        '401':
          description: Invalid or expired token
          content:
            application/json:
              examples:
                Expired token:
                  summary: Expired token
                  value:
                    detail: 'Token time expired: Signature has expired.'
                Invalid token:
                  summary: Invalid token
                  value:
                    detail: Invalid token
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Not found:
                  summary: Not found
                  value:
                    summary: Unknown id
                    detail: Not Found
        '422':
          description: Error - 422
          content:
            application/json:
              examples:
                Validation error:
                  summary: Validation error
                  value:
                    summary: Invalid input
                    detail:
                    - type: parsing
                      loc:
                      - path
                      - query
                      - body
                      msg: invalid input
                      input: '-1'
components:
  schemas:
    MagistrateJudgeData:
      properties:
        name:
          type: string
          title: Name
        magistrateJudgeId:
          type: integer
          title: Magistratejudgeid
        initials:
          type: string
          title: Initials
        caseCountByCourt:
          items:
            $ref: '#/components/schemas/CaseCountByCourt'
          type: array
          title: Casecountbycourt
      additionalProperties: false
      type: object
      required:
      - name
      - magistrateJudgeId
      - initials
      - caseCountByCourt
      title: MagistrateJudgeData
    StateJudgeData:
      properties:
        name:
          type: string
          title: Name
        stateJudgeId:
          type: integer
          title: Statejudgeid
        courtPosting:
          type: string
          title: Courtposting
      additionalProperties: false
      type: object
      required:
      - name
      - stateJudgeId
      - courtPosting
      title: StateJudgeData
    CaseCountByCourt:
      properties:
        court:
          type: string
          title: Court
        count:
          type: integer
          title: Count
      additionalProperties: false
      type: object
      required:
      - court
      - count
      title: CaseCountByCourt
  securitySchemes:
    JwtAccessBearer:
      type: http
      scheme: bearer
